name 'chocolatey-server'
maintainer 'Laura Melton'
maintainer_email 'melton@tamu.edu'
license 'All Rights Reserved'
description 'Installs/Configures chocolatey-server'
long_description 'Installs/Configures chocolatey-server'
version '0.1.5'
chef_version '>= 13.0'

depends 'chocolatey'
depends 'windows'
depends 'iis'

issues_url 'https://github.com/tamucookbooks/chocolatey-server/issues'
source_url 'https://github.com/tamucookbooks/chocolatey-server'
